# Generated by Django 3.0.5 on 2020-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authors_list', '0003_auto_20200422_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('edition', models.PositiveIntegerField(null=True)),
                ('publication_year', models.IntegerField(null=True)),
                ('Authors', models.ManyToManyField(to='Authors_list.Authors')),
            ],
        ),
    ]
