# Generated by Django 3.0.5 on 2020-04-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors_list', '0001_initial'),
        ('core_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authors',
        ),
        migrations.AddField(
            model_name='product',
            name='authors',
            field=models.ManyToManyField(to='Authors_list.Authors'),
        ),
    ]
