# Generated by Django 3.0.5 on 2020-04-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authors_list', '0003_auto_20200422_1247'),
        ('core_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Authors',
        ),
        migrations.AddField(
            model_name='product',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='Authors_list.Authors'),
        ),
    ]
