# Generated by Django 3.0.5 on 2020-04-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_list', '0002_auto_20200423_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='authors',
            new_name='authors_name',
        ),
    ]
