# Generated by Django 3.0.5 on 2020-04-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_list', '0002_auto_20200417_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authors',
        ),
        migrations.AddField(
            model_name='product',
            name='authors',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
