# Generated by Django 3.0.5 on 2020-04-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors_list', '0003_auto_20200422_1247'),
        ('core_list', '0003_auto_20200423_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authors_name',
        ),
        migrations.AddField(
            model_name='product',
            name='Authors',
            field=models.ManyToManyField(to='Authors_list.Authors'),
        ),
    ]
