# Generated by Django 3.0.5 on 2020-04-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
