# Generated by Django 3.0.5 on 2020-04-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authors_list', '0002_auto_20200420_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='author_name',
        ),
    ]
